"""Add finding evidence traceability

Revision ID: 223af09b0ed9
Revises: d2900707275f
Create Date: 2026-08-17 19:50:32.556003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223af09b0ed9'
down_revision: Union[str, Sequence[str], None] = 'd2900707275f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finding_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('evidence_chunk_id', sa.UUID(), nullable=False),
    sa.Column('relevance_distance', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_chunk_id'], ['evidence_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id', 'evidence_chunk_id', name='uq_finding_evidence_finding_chunk')
    )
    op.create_index(op.f('ix_finding_evidence_evidence_chunk_id'), 'finding_evidence', ['evidence_chunk_id'], unique=False)
    op.create_index(op.f('ix_finding_evidence_finding_id'), 'finding_evidence', ['finding_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finding_evidence_finding_id'), table_name='finding_evidence')
    op.drop_index(op.f('ix_finding_evidence_evidence_chunk_id'), table_name='finding_evidence')
    op.drop_table('finding_evidence')
    # ### end Alembic commands ###
